name: "Hola acciones"
description: "Acciones de github"
author: "Sergio Bateca"

inputs:
  INPUT_MY_NAME:
    description: "variable para el nombre"
    required: true
    default: "Mundo"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
